Fix Compiler error
This error only occours when built with libusb-1.0
It does not occour with libusb version 0.1 but we should not be using
this any longer it is obsolete.

martin@Ace:LCDproc$ cd server/drivers/
martin@Ace:drivers$ make
gcc -DHAVE_CONFIG_H -I. -I../..  -I../..  -I/usr/include/libusb-1.0  -fPIC -Wall  -g -O -Wno-unused-function -MT picolcd-picolcd.o -MD -MP -MF .deps/picolcd-picolcd.Tpo -c -o picolcd-picolcd.o `test -f 'picolcd.c' || echo './'`picolcd.c
picolcd.c: In function ‘picolcd_send’:
picolcd.c:1882:10: error: ‘RPT_WARN’ undeclared (first use in this function)
   report(RPT_WARN, "libusb_interrupt_transfer error %d, sent %d of %d bytes\n",
          ^
picolcd.c:1882:10: note: each undeclared identifier is reported only once for each function it appears in
Makefile:1484: recipe for target 'picolcd-picolcd.o' failed
make: *** [picolcd-picolcd.o] Error 1