Add missing ioctl header
The spidev.h header uses macros from linux/ioctl.h. Add this header
explicitly since some libc, like musl, do not include it implicitly.
This fixes the following build failure:

In file included from .../sysroot/usr/include/sys/ioctl.h:7:0,
                 from hd44780-spi.c:31:
hd44780-spi.c: In function ‘spi_transfer’:
hd44780-spi.c:89:24: error: ‘_IOC_SIZEBITS’ undeclared (first use in this function)
  status = ioctl(p->fd, SPI_IOC_MESSAGE(1), &xfer);
                        ^